services:
  fn-message-bots:
    build: .
    container_name: fn-message-bots
    restart: unless-stopped
    ports:
      - 18080:18080
    volumes:
      - ./data/logs:/app/data/logs:rw
      - ./data/cursor:/app/data/cursor:rw
      - /usr/trim/var/eventlogger_service:/usr/trim/var/eventlogger_service:ro
      - ./config:/app/config:rw
    environment:
      - TZ=Asia/Shanghai
